application/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::namespace('Admin')->group(function () {
    Route::resource('/', 'HomeController');
    Route::resource('costumer', 'CostumerController');
    Route::resource('product', 'ProductController');
});

application/resources/views/admin/costumer.blade.php
@extends('admin.dashboard')

@section('customStyle')
<style>
.modal-body {
    max-height: calc(100vh - 210px);
    overflow-y: auto;
}
</style>
@endsection

@section('content')
<div style="margin-top:2%" class="kt-portlet">
    <div class="kt-portlet__head bg-warning" style="justify-content: center">
        <div class="kt-portlet__head-label">
            <h3 class="kt-portlet__head-title" style="font-size: 200%">
                TEST STAND KHRISNA
            </h3>
        </div>
    </div>
    <div class="kt-portlet__body">

        @if($errors->any())
            {!! implode('', $errors->all('<div class="alert alert-danger">:message</div>')) !!}
        @endif
        
        @if (\Session::has('success'))
            <div class="alert alert-success">
                {!! Session::get('success') !!}
            </div>
        @endif

        <form class="kt-form" method="POST" action="{{route('costumer.store')}}">
            @csrf
            <div class="kt-portlet__body">
                <div class="kt-section kt-section--first">
                    <div class="form-group">
                        <label>Company :</label>
                        <input type="text" name="name" class="form-control" placeholder="Enter company name" required>
                        <span class="form-text text-muted">Costumer company name...</span>
                    </div>
                </div>
            </div>
            <div class="kt-portlet__foot">
                <div class="kt-form__actions">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <button type="reset" class="btn btn-secondary">Cancel</button>
                </div>
            </div>
        </form>

        {{$costumer->links()}}
        <table class="table table-striped- table-bordered table-hover table-checkable" id="kt_table_1">
            <thead>
                <th>
                    Company
                </th>
                <th>
                    Aksi
                </th>
            </thead>
            <tbody>
                @foreach ($costumer as $item)
                    <tr>
                        <td>
                            {{$item->name}}
                        </td>
                        <td>
                            <button type="button" class="btn btn-danger" onclick="deleteData({{$item->id}})">Delete</button>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
@endsection

@section('customScript')
<script type="text/javascript">
    $(document).ready(function() {
        let table = $('#kt_table_1').DataTable();
    } );

    function deleteData(id){
        $.ajax({
        url: "{{url('costumer')}}"+'/'+id,
        type: 'delete',
        data: {_token: $("input[name=_token]").val()},
        success: function(response){
            window.location.reload();
        }
      });
    }
</script>
@endsection

application/resources/views/admin/dashboard.blade.php
@extends('layout_metronic')

@section('dashboard')
<!-- begin:: Header Mobile -->
<div id="kt_header_mobile" class="kt-header-mobile  kt-header-mobile--fixed ">
    <div class="kt-header-mobile__toolbar">
        <button class="kt-header-mobile__toggler kt-header-mobile__toggler--left" id="kt_aside_mobile_toggler"><span></span></button>
    </div>
</div>

<!-- end:: Header Mobile -->
<div class="kt-grid kt-grid--hor kt-grid--root">
    <div class="kt-grid__item kt-grid__item--fluid kt-grid kt-grid--ver kt-page">

        <!-- begin:: Aside -->
        <button class="kt-aside-close " id="kt_aside_close_btn"><i class="la la-close"></i></button>
        <div class="kt-aside  kt-aside--fixed  kt-grid__item kt-grid kt-grid--desktop kt-grid--hor-desktop" id="kt_aside">

            <!-- begin:: Aside -->
            <div class="kt-aside__brand kt-grid__item " id="kt_aside_brand">
                <div class="kt-aside__brand-tools">
                    <button class="kt-aside__brand-aside-toggler" id="kt_aside_toggler">
                        <span><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1" class="kt-svg-icon">
                                <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                    <polygon id="Shape" points="0 0 24 0 24 24 0 24" />
                                    <path d="M5.29288961,6.70710318 C4.90236532,6.31657888 4.90236532,5.68341391 5.29288961,5.29288961 C5.68341391,4.90236532 6.31657888,4.90236532 6.70710318,5.29288961 L12.7071032,11.2928896 C13.0856821,11.6714686 13.0989277,12.281055 12.7371505,12.675721 L7.23715054,18.675721 C6.86395813,19.08284 6.23139076,19.1103429 5.82427177,18.7371505 C5.41715278,18.3639581 5.38964985,17.7313908 5.76284226,17.3242718 L10.6158586,12.0300721 L5.29288961,6.70710318 Z" id="Path-94" fill="#000000" fill-rule="nonzero" transform="translate(8.999997, 11.999999) scale(-1, 1) translate(-8.999997, -11.999999) " />
                                    <path d="M10.7071009,15.7071068 C10.3165766,16.0976311 9.68341162,16.0976311 9.29288733,15.7071068 C8.90236304,15.3165825 8.90236304,14.6834175 9.29288733,14.2928932 L15.2928873,8.29289322 C15.6714663,7.91431428 16.2810527,7.90106866 16.6757187,8.26284586 L22.6757187,13.7628459 C23.0828377,14.1360383 23.1103407,14.7686056 22.7371482,15.1757246 C22.3639558,15.5828436 21.7313885,15.6103465 21.3242695,15.2371541 L16.0300699,10.3841378 L10.7071009,15.7071068 Z" id="Path-94" fill="#000000" fill-rule="nonzero" opacity="0.3" transform="translate(15.999997, 11.999999) scale(-1, 1) rotate(-270.000000) translate(-15.999997, -11.999999) " />
                                </g>
                            </svg></span>
                        <span><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1" class="kt-svg-icon">
                                <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                    <polygon id="Shape" points="0 0 24 0 24 24 0 24" />
                                    <path d="M12.2928955,6.70710318 C11.9023712,6.31657888 11.9023712,5.68341391 12.2928955,5.29288961 C12.6834198,4.90236532 13.3165848,4.90236532 13.7071091,5.29288961 L19.7071091,11.2928896 C20.085688,11.6714686 20.0989336,12.281055 19.7371564,12.675721 L14.2371564,18.675721 C13.863964,19.08284 13.2313966,19.1103429 12.8242777,18.7371505 C12.4171587,18.3639581 12.3896557,17.7313908 12.7628481,17.3242718 L17.6158645,12.0300721 L12.2928955,6.70710318 Z" id="Path-94" fill="#000000" fill-rule="nonzero" />
                                    <path d="M3.70710678,15.7071068 C3.31658249,16.0976311 2.68341751,16.0976311 2.29289322,15.7071068 C1.90236893,15.3165825 1.90236893,14.6834175 2.29289322,14.2928932 L8.29289322,8.29289322 C8.67147216,7.91431428 9.28105859,7.90106866 9.67572463,8.26284586 L15.6757246,13.7628459 C16.0828436,14.1360383 16.1103465,14.7686056 15.7371541,15.1757246 C15.3639617,15.5828436 14.7313944,15.6103465 14.3242754,15.2371541 L9.03007575,10.3841378 L3.70710678,15.7071068 Z" id="Path-94" fill="#000000" fill-rule="nonzero" opacity="0.3" transform="translate(9.000003, 11.999999) rotate(-270.000000) translate(-9.000003, -11.999999) " />
                                </g>
                            </svg></span>
                    </button>
                </div>
            </div>

            <!-- end:: Aside -->

            <!-- begin:: Aside Menu -->
            <div class="kt-aside-menu-wrapper kt-grid__item kt-grid__item--fluid bg-dark" id="kt_aside_menu_wrapper">
                <div id="kt_aside_menu" class="kt-aside-menu " data-ktmenu-vertical="1" data-ktmenu-scroll="1" data-ktmenu-dropdown-timeout="500">
                    <ul class="kt-menu__nav">
                        <li class="kt-menu__item " aria-haspopup="true"><a href="{{route("index")}}" class="kt-menu__link "><span class="kt-menu__link-icon"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1" class="kt-svg-icon">
                            <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                <rect id="bound" x="0" y="0" width="24" height="24" />
                                <path d="M5,3 L6,3 C6.55228475,3 7,3.44771525 7,4 L7,20 C7,20.5522847 6.55228475,21 6,21 L5,21 C4.44771525,21 4,20.5522847 4,20 L4,4 C4,3.44771525 4.44771525,3 5,3 Z M10,3 L11,3 C11.5522847,3 12,3.44771525 12,4 L12,20 C12,20.5522847 11.5522847,21 11,21 L10,21 C9.44771525,21 9,20.5522847 9,20 L9,4 C9,3.44771525 9.44771525,3 10,3 Z" id="Combined-Shape" fill="#000000" />
                                <rect id="Rectangle-Copy-2" fill="#000000" opacity="0.3" transform="translate(17.825568, 11.945519) rotate(-19.000000) translate(-17.825568, -11.945519) " x="16.3255682" y="2.94551858" width="3" height="18" rx="1" />
                            </g>
                        </svg></span><span class="kt-menu__link-text">Home</span></a></li>
                        <li class="kt-menu__item " aria-haspopup="true"><a href="{{route("costumer.create")}}" class="kt-menu__link "><span class="kt-menu__link-icon"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1" class="kt-svg-icon">
                            <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                <rect id="bound" x="0" y="0" width="24" height="24" />
                                <path d="M5,3 L6,3 C6.55228475,3 7,3.44771525 7,4 L7,20 C7,20.5522847 6.55228475,21 6,21 L5,21 C4.44771525,21 4,20.5522847 4,20 L4,4 C4,3.44771525 4.44771525,3 5,3 Z M10,3 L11,3 C11.5522847,3 12,3.44771525 12,4 L12,20 C12,20.5522847 11.5522847,21 11,21 L10,21 C9.44771525,21 9,20.5522847 9,20 L9,4 C9,3.44771525 9.44771525,3 10,3 Z" id="Combined-Shape" fill="#000000" />
                                <rect id="Rectangle-Copy-2" fill="#000000" opacity="0.3" transform="translate(17.825568, 11.945519) rotate(-19.000000) translate(-17.825568, -11.945519) " x="16.3255682" y="2.94551858" width="3" height="18" rx="1" />
                            </g>
                        </svg></span><span class="kt-menu__link-text">Costumer</span></a></li>
                        <li class="kt-menu__item " aria-haspopup="true"><a href="{{route("product.create")}}" class="kt-menu__link "><span class="kt-menu__link-icon"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1" class="kt-svg-icon">
                            <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                <rect id="bound" x="0" y="0" width="24" height="24" />
                                <path d="M5,3 L6,3 C6.55228475,3 7,3.44771525 7,4 L7,20 C7,20.5522847 6.55228475,21 6,21 L5,21 C4.44771525,21 4,20.5522847 4,20 L4,4 C4,3.44771525 4.44771525,3 5,3 Z M10,3 L11,3 C11.5522847,3 12,3.44771525 12,4 L12,20 C12,20.5522847 11.5522847,21 11,21 L10,21 C9.44771525,21 9,20.5522847 9,20 L9,4 C9,3.44771525 9.44771525,3 10,3 Z" id="Combined-Shape" fill="#000000" />
                                <rect id="Rectangle-Copy-2" fill="#000000" opacity="0.3" transform="translate(17.825568, 11.945519) rotate(-19.000000) translate(-17.825568, -11.945519) " x="16.3255682" y="2.94551858" width="3" height="18" rx="1" />
                            </g>
                        </svg></span><span class="kt-menu__link-text">Product</span></a></li>
                    </ul>
                </div>
            </div>

            <!-- end:: Aside Menu -->
        </div>

        <!-- end:: Aside -->
    </div>
</div>

@endsection

application/resources/views/admin/index.blade.php
@extends('admin.dashboard')

@section('customStyle')
<style>
.modal-body {
    max-height: calc(100vh - 210px);
    overflow-y: auto;
}
</style>
@endsection

@section('content')
<div style="margin-top:2%" class="kt-portlet">
    <div class="kt-portlet__head bg-warning" style="justify-content: center">
        <div class="kt-portlet__head-label">
            <h3 class="kt-portlet__head-title" style="font-size: 200%">
                TEST STAND KHRISNA
            </h3>
        </div>
    </div>
    <div class="kt-portlet__body">
        
        {{$costumer->links()}}
        <table class="table table-striped- table-bordered table-hover table-checkable" id="kt_table_1">
            <thead>
                <th>
                    Company
                </th>
                <th>
                    Aksi
                </th>
            </thead>
            <tbody>
                @foreach ($costumer as $item)
                    <tr>
                        <td>
                            {{$item->name}}
                        </td>
                        <td>
                            <button type="button" data-toggle="modal" onclick="getData({{$item->id}},1)" data-target="#kt_modal_1" class="btn btn-warning detailProduct">Products</button>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        <div class="modal fade" id="kt_modal_1" data-id="" data-page="1" tabindex="-1" data-page="1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel"></h5>
                    </div>
                    <div class="modal-body">
                        <button onclick="backPage()">back</button>
                        <button onclick="nextPage()">next</button>
                        <div id="table-content"></div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
        
        
    </div>
</div>
@endsection

@section('customScript')
   <script type="text/javascript">
        $(document).ready(function() {
            let table = $('#kt_table_1').DataTable(); 
        });

        function getData(id,page){
            $('#kt_modal_1').data('id', id);

            $('#exampleModalLabel').html($(this).data('name'));

            $.getJSON("{{url('costumer')}}"+"/"+id+"?page="+page, function(result){
                if(result.page != ""){
                    $('#table-content').html(result.page);
                    $('#kt_modal_1').data('page',page);
                }else{
                    alert('Last Page');
                }
            });
        }

        function backPage(){
            var currentId = $('#kt_modal_1').data('id');
            var currentPage = $('#kt_modal_1').data('page');

            var backPage = currentPage-1;
            if(backPage != 0){;
                getData(currentId,backPage);
            }
        }

        function nextPage() {
            var currentId = $('#kt_modal_1').data('id');
            var currentPage = $('#kt_modal_1').data('page');

            var nextPage = currentPage+1;

            if(nextPage != 0){
                getData(currentId,nextPage);
            }
        }
    </script>
@endsection

application/resources/views/admin/product.blade.php
@extends('admin.dashboard')

@section('customStyle')
<style>
.modal-body {
    max-height: calc(100vh - 210px);
    overflow-y: auto;
}
</style>
@endsection

@section('content')
<div style="margin-top:2%" class="kt-portlet">
    <div class="kt-portlet__head bg-warning" style="justify-content: center">
        <div class="kt-portlet__head-label">
            <h3 class="kt-portlet__head-title" style="font-size: 200%">
                TEST STAND KHRISNA
            </h3>
        </div>
    </div>
    <div class="kt-portlet__body">

        @if($errors->any())
            {!! implode('', $errors->all('<div class="alert alert-danger">:message</div>')) !!}
        @endif
        
        @if (\Session::has('success'))
            <div class="alert alert-success">
                {!! Session::get('success') !!}
            </div>
        @endif

        <form class="kt-form" method="POST" action="{{route('product.store')}}">
            @csrf
            <div class="kt-portlet__body">
                <div class="kt-section kt-section--first">
                    <div class="form-group">
                        <label>Product:</label>
                        <input type="text" name="name" class="form-control" placeholder="Enter product" required>
                        <span class="form-text text-muted">Please enter your product</span>
                    </div>
                </div>
            </div>
            <div class="kt-portlet__foot">
                <div class="kt-form__actions">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <button type="reset" class="btn btn-secondary">Cancel</button>
                </div>
            </div>
        </form>
        {{$product->links()}}
        <table class="table table-striped- table-bordered table-hover table-checkable" id="kt_table_1">
            <thead>
                <th>
                    Product
                </th>
                <th>
                    Aksi
                </th>
            </thead>
            <tbody>
                @foreach ($product as $item)
                    <tr>
                        <td>
                            {{$item->name}}
                        </td>
                        <td>
                            <button type="button" class="btn btn-danger" onclick="deleteData({{$item->id}})">Delete</button>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
@endsection

@section('customScript')
<script type="text/javascript">
    $(document).ready(function() {
        let table = $('#kt_table_1').DataTable();
    } );

    function deleteData(id){
        $.ajax({
        url: "{{url('product')}}"+'/'+id,
        type: 'delete',
        data: {_token: $("input[name=_token]").val()},
        success: function(response){
            window.location.reload();
        }
      });
    }
</script>
@endsection